set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

if(DEFINED ARM_COMPILER_PATH AND NOT ARM_COMPILER_PATH STREQUAL "")
    file(TO_CMAKE_PATH "${ARM_COMPILER_PATH}" ARM_COMPILER_PATH_CMAKE)
    set(_ARM_TOOLCHAIN_PREFIX "${ARM_COMPILER_PATH_CMAKE}/")
else()
    set(_ARM_TOOLCHAIN_PREFIX "")
endif()

set(CMAKE_C_COMPILER "${_ARM_TOOLCHAIN_PREFIX}arm-none-eabi-gcc" CACHE FILEPATH "ARM C compiler")
set(CMAKE_CXX_COMPILER "${_ARM_TOOLCHAIN_PREFIX}arm-none-eabi-g++" CACHE FILEPATH "ARM C++ compiler")
set(CMAKE_ASM_COMPILER "${_ARM_TOOLCHAIN_PREFIX}arm-none-eabi-gcc" CACHE FILEPATH "ARM ASM compiler")
set(CMAKE_OBJCOPY "${_ARM_TOOLCHAIN_PREFIX}arm-none-eabi-objcopy" CACHE FILEPATH "ARM objcopy")
set(CMAKE_SIZE "${_ARM_TOOLCHAIN_PREFIX}arm-none-eabi-size" CACHE FILEPATH "ARM size")
set(CMAKE_OBJDUMP "${_ARM_TOOLCHAIN_PREFIX}arm-none-eabi-objdump" CACHE FILEPATH "ARM objdump")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
