// Generated by tools/generate_fault_schema.py. Do not edit.
export const FAULT_SCHEMA_VERSION = 1 as const;

export const FaultSource = {
  AXIS: 1,
  MOTOR: 2,
  ENCODER: 3,
  CONTROLLER: 4,
  SAFETY: 5,
  POWER_STAGE: 6,
  ISR: 7,
  CAN: 8,
  USB: 9
} as const;

export type FaultSource = typeof FaultSource[keyof typeof FaultSource];

export const FaultCode = {
  NONE: 0,
  TIMEOUT: 1,
  FEEDBACK_MISSING: 2,
  ENCODER_ERROR: 3,
  CONTROLLER_REJECTED: 4,
  CONTROLLER_ERROR: 5,
  MOTOR_ERROR: 6,
  POWER_STAGE_SHUTDOWN: 7,
  INVALID_STATE: 8,
  COMPATIBILITY_PROJECTION: 9,
  ESTOP_REQUESTED: 10
} as const;

export type FaultCode = typeof FaultCode[keyof typeof FaultCode];

export const FaultSite = {
  UNKNOWN: 0,
  AXIS_WATCHDOG: 1,
  CLOSED_LOOP_PREPARE: 2,
  ENCODER_UPDATE: 3,
  CONTROLLER_UPDATE: 4,
  MOTOR_UPDATE: 5,
  POWER_STAGE_ARM: 6,
  COMMAND_TIMEOUT: 7,
  STATE_TRANSITION: 8,
  COMPATIBILITY_PROJECTION: 9,
  CAN_ESTOP: 10
} as const;

export type FaultSite = typeof FaultSite[keyof typeof FaultSite];

export const FaultSeverity = {
  INFO: 0,
  WARNING: 1,
  RECOVERABLE: 2,
  LATCHED: 3,
  IMMEDIATE_SHUTDOWN: 4
} as const;

export type FaultSeverity = typeof FaultSeverity[keyof typeof FaultSeverity];
