#!/usr/bin/env python3
"""Generate C++, Python, and TypeScript fault-code bindings from one JSON source."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def cpp_enum(name: str, values: list[dict[str, object]], underlying: str) -> str:
    lines = [f"enum class {name} : {underlying} {{"]
    lines.extend(f"    {item['name']} = {item['value']}," for item in values)
    lines.append("};")
    return "\n".join(lines)


def write_cpp(schema: dict[str, object], output: Path) -> None:
    text = """// Generated by tools/generate_fault_schema.py. Do not edit.\n#ifndef ODRIVE_FAULT_CODES_GENERATED_HPP\n#define ODRIVE_FAULT_CODES_GENERATED_HPP\n\n#include <cstdint>\n\nnamespace odrive::fault {\n"""
    text += f"constexpr uint16_t kSchemaVersion = {schema['schema_version']};\n\n"
    text += cpp_enum("FaultSource", schema["fault_sources"], "uint16_t") + "\n\n"
    text += cpp_enum("FaultCode", schema["fault_codes"], "uint16_t") + "\n\n"
    text += cpp_enum("FaultSite", schema["fault_sites"], "uint16_t") + "\n\n"
    text += cpp_enum("FaultSeverity", schema["fault_severities"], "uint8_t")
    text += "\n\n}  // namespace odrive::fault\n\n#endif\n"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8")


def write_python(schema: dict[str, object], output: Path) -> None:
    text = "# Generated by tools/generate_fault_schema.py. Do not edit.\nfrom enum import IntEnum\n\n"
    text += f"SCHEMA_VERSION = {schema['schema_version']}\n\n"
    for key, enum_name in (("fault_sources", "FaultSource"), ("fault_codes", "FaultCode"),
                           ("fault_sites", "FaultSite"), ("fault_severities", "FaultSeverity")):
        text += f"class {enum_name}(IntEnum):\n"
        text += "\n".join(f"    {item['name']} = {item['value']}" for item in schema[key]) + "\n\n"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8")


def write_typescript(schema: dict[str, object], output: Path) -> None:
    text = "// Generated by tools/generate_fault_schema.py. Do not edit.\n"
    text += f"export const FAULT_SCHEMA_VERSION = {schema['schema_version']} as const;\n\n"
    for key, name in (("fault_sources", "FaultSource"), ("fault_codes", "FaultCode"),
                      ("fault_sites", "FaultSite"), ("fault_severities", "FaultSeverity")):
        text += f"export const {name} = {{\n"
        text += "\n".join(
            f"  {item['name']}: {item['value']}" + ("," if index + 1 < len(schema[key]) else "")
            for index, item in enumerate(schema[key]))
        text += "\n} as const;\n\n"
        text += f"export type {name} = typeof {name}[keyof typeof {name}];\n\n"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--schema", default="docs/fault_schema.json")
    parser.add_argument("--cpp-output")
    parser.add_argument("--python-output")
    parser.add_argument("--typescript-output")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    schema = json.loads((root / args.schema).read_text(encoding="utf-8"))
    if args.cpp_output:
        write_cpp(schema, Path(args.cpp_output))
    if args.python_output:
        write_python(schema, root / args.python_output)
    if args.typescript_output:
        write_typescript(schema, root / args.typescript_output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
