/*
 * Production profile for the trimmed ODrive v3 single-axis firmware.
 *
 * Keep this file C-compatible: it is included by both C and C++ firmware code.
 * Values can still be overridden from the build system with -D..., but the
 * defaults below define the production-safe profile used by this branch.
 */

#ifndef __ODRIVE_PRODUCTION_CONFIG_H
#define __ODRIVE_PRODUCTION_CONFIG_H

#ifndef ODRIVE_PRODUCTION_SINGLE_AXIS
#define ODRIVE_PRODUCTION_SINGLE_AXIS 1
#endif

#ifndef ODRIVE_PRODUCTION_CAN_BAUD
#define ODRIVE_PRODUCTION_CAN_BAUD 1000000UL
#endif

#ifndef ODRIVE_PRODUCTION_CAN_NODE_ID
#define ODRIVE_PRODUCTION_CAN_NODE_ID 0UL
#endif

#ifndef ODRIVE_PRODUCTION_MOTOR_CALIBRATION_CURRENT
#define ODRIVE_PRODUCTION_MOTOR_CALIBRATION_CURRENT 2.0f
#endif

#ifndef ODRIVE_PRODUCTION_MOTOR_CURRENT_LIMIT
#define ODRIVE_PRODUCTION_MOTOR_CURRENT_LIMIT 5.0f
#endif

#ifndef ODRIVE_PRODUCTION_AXIS_CALIBRATION_CURRENT
#define ODRIVE_PRODUCTION_AXIS_CALIBRATION_CURRENT 2.0f
#endif

#ifndef ODRIVE_PRODUCTION_PROFILE_VERSION
#define ODRIVE_PRODUCTION_PROFILE_VERSION 0x0001u
#endif

/*
 * Motor / encoder / hardware model constants for the production build.
 * These are baked per motor model (one build = one motor model). The firmware
 * force-overwrites the corresponding Config_t fields from these on every boot
 * (in apply_config), so NVM never holds a stale/wrong motor-model value, and
 * the customer CAN/YAML face does not expose setters for them. Load-dependent
 * tuning (gains, current_lim, trap_traj, ControlTimeout) stays in NVM.
 *
 * Values are C-compatible (enums as numbers) because this header is included
 * by C and C++ code. motor_type: 0=HIGH_CURRENT. encoder.mode: 0x106 =
 * SPI_ABS_MT6826S_VERNIER.
 */
#ifndef ODRIVE_PRODUCTION_MOTOR_TYPE
#define ODRIVE_PRODUCTION_MOTOR_TYPE 0  /* MOTOR_TYPE_HIGH_CURRENT */
#endif
#ifndef ODRIVE_PRODUCTION_POLE_PAIRS
#define ODRIVE_PRODUCTION_POLE_PAIRS 14
#endif
#ifndef ODRIVE_PRODUCTION_TORQUE_CONSTANT
#define ODRIVE_PRODUCTION_TORQUE_CONSTANT 0.04f
#endif
#ifndef ODRIVE_PRODUCTION_RESISTANCE_CALIB_MAX_VOLTAGE
#define ODRIVE_PRODUCTION_RESISTANCE_CALIB_MAX_VOLTAGE 3.0f
#endif
#ifndef ODRIVE_PRODUCTION_REQUESTED_CURRENT_RANGE
#define ODRIVE_PRODUCTION_REQUESTED_CURRENT_RANGE 20.0f
#endif
#ifndef ODRIVE_PRODUCTION_INVERTER_TEMP_LIMIT_LOWER
#define ODRIVE_PRODUCTION_INVERTER_TEMP_LIMIT_LOWER 100.0f
#endif
#ifndef ODRIVE_PRODUCTION_INVERTER_TEMP_LIMIT_UPPER
#define ODRIVE_PRODUCTION_INVERTER_TEMP_LIMIT_UPPER 120.0f
#endif
#ifndef ODRIVE_PRODUCTION_ENCODER_MODE
#define ODRIVE_PRODUCTION_ENCODER_MODE 0x106  /* SPI_ABS_MT6826S_VERNIER */
#endif
#ifndef ODRIVE_PRODUCTION_ENCODER_CPR
#define ODRIVE_PRODUCTION_ENCODER_CPR 32768
#endif
#ifndef ODRIVE_PRODUCTION_ABS_SPI_CS_GPIO_PIN
#define ODRIVE_PRODUCTION_ABS_SPI_CS_GPIO_PIN 2
#endif
#ifndef ODRIVE_PRODUCTION_ABS_SPI_AUX_CS_GPIO_PIN
#define ODRIVE_PRODUCTION_ABS_SPI_AUX_CS_GPIO_PIN 4
#endif
#ifndef ODRIVE_PRODUCTION_VERNIER_VIRTUAL_CPR
#define ODRIVE_PRODUCTION_VERNIER_VIRTUAL_CPR 32768
#endif
#ifndef ODRIVE_PRODUCTION_VERNIER_MAIN_RATIO
#define ODRIVE_PRODUCTION_VERNIER_MAIN_RATIO 42.0f
#endif
#ifndef ODRIVE_PRODUCTION_VERNIER_AUX_RATIO
#define ODRIVE_PRODUCTION_VERNIER_AUX_RATIO 41.0f
#endif
#ifndef ODRIVE_PRODUCTION_VERNIER_MAIN_REVERSED
#define ODRIVE_PRODUCTION_VERNIER_MAIN_REVERSED 1
#endif
#ifndef ODRIVE_PRODUCTION_VERNIER_AUX_REVERSED
#define ODRIVE_PRODUCTION_VERNIER_AUX_REVERSED 0
#endif
#ifndef ODRIVE_PRODUCTION_VERNIER_OUTPUT_REVERSED
#define ODRIVE_PRODUCTION_VERNIER_OUTPUT_REVERSED 0
#endif
#ifndef ODRIVE_PRODUCTION_VERNIER_USE_PHASE_DIFFERENCE
#define ODRIVE_PRODUCTION_VERNIER_USE_PHASE_DIFFERENCE 1
#endif
#ifndef ODRIVE_PRODUCTION_MT6826S_SPI_MODE
#define ODRIVE_PRODUCTION_MT6826S_SPI_MODE 3
#endif
#ifndef ODRIVE_PRODUCTION_MT6826S_SPI_PRESCALER
#define ODRIVE_PRODUCTION_MT6826S_SPI_PRESCALER 8
#endif
#ifndef ODRIVE_PRODUCTION_VERNIER_ERR_ACCEPT
#define ODRIVE_PRODUCTION_VERNIER_ERR_ACCEPT 0.02f
#endif
#ifndef ODRIVE_PRODUCTION_VERNIER_ERR_REJECT
#define ODRIVE_PRODUCTION_VERNIER_ERR_REJECT 0.08f
#endif
#ifndef ODRIVE_PRODUCTION_BRAKE_RESISTANCE
#define ODRIVE_PRODUCTION_BRAKE_RESISTANCE 2.0f
#endif
#ifndef ODRIVE_PRODUCTION_ENABLE_BRAKE_RESISTOR
#define ODRIVE_PRODUCTION_ENABLE_BRAKE_RESISTOR 1
#endif
#ifndef ODRIVE_PRODUCTION_DC_BUS_UNDERVOLTAGE
#define ODRIVE_PRODUCTION_DC_BUS_UNDERVOLTAGE 14.0f
#endif
#ifndef ODRIVE_PRODUCTION_DC_BUS_OVERVOLTAGE
#define ODRIVE_PRODUCTION_DC_BUS_OVERVOLTAGE 65.0f
#endif

#endif /* __ODRIVE_PRODUCTION_CONFIG_H */
